"""Optional renderer adapters and shared capability diagnostics."""

from .diagnostics import CapabilityEntry, CapabilityReport
from .mitsuba import (
    DEFAULT_MITSUBA_CONFIG,
    MITSUBA_ADAPTER,
    MITSUBA_ADAPTER_VERSION,
    MitsubaExportConfig,
    MitsubaExportError,
    MitsubaFieldConversion,
    MitsubaRenderResult,
    PreparedMitsubaScene,
    convert_optical_fields,
    mitsuba_capability_report,
    prepare_mitsuba_scene,
    render_mitsuba,
)
from .openvdb import (
    DEFAULT_OPENVDB_CONFIG,
    OPENVDB_ADAPTER,
    OPENVDB_ADAPTER_VERSION,
    OpenVDBExportConfig,
    OpenVDBExportError,
    OpenVDBExportResult,
    OpenVDBFieldConversion,
    convert_openvdb_fields,
    export_openvdb,
    openvdb_capability_report,
)

__all__ = [
    "DEFAULT_MITSUBA_CONFIG",
    "DEFAULT_OPENVDB_CONFIG",
    "MITSUBA_ADAPTER",
    "MITSUBA_ADAPTER_VERSION",
    "OPENVDB_ADAPTER",
    "OPENVDB_ADAPTER_VERSION",
    "CapabilityEntry",
    "CapabilityReport",
    "MitsubaExportConfig",
    "MitsubaExportError",
    "MitsubaFieldConversion",
    "MitsubaRenderResult",
    "OpenVDBExportConfig",
    "OpenVDBExportError",
    "OpenVDBExportResult",
    "OpenVDBFieldConversion",
    "PreparedMitsubaScene",
    "convert_openvdb_fields",
    "convert_optical_fields",
    "export_openvdb",
    "mitsuba_capability_report",
    "openvdb_capability_report",
    "prepare_mitsuba_scene",
    "render_mitsuba",
]
